version: '3.8'

services:
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=osm-db
      - MYSQL_ROOT_PASSWORD=${OSM_DB_PWD}
      - MYSQL_USER=osm-user
      - MYSQL_PASSWORD=${OSM_DB_PWD}
    ports:
      - ${OSM_DB_PORT}:3306
    expose:
      - ${OSM_DB_PORT}
    container_name: osm-database
    volumes:
      - mysql:/var/lib/mysql

  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - ${OSM_REDIS_PORT}:6379
    expose:
      - ${OSM_DB_PORT}
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${OSM_REDIS_PWD}
    volumes:
      - redis-data:/data

volumes:
  mysql:
    driver: local
  redis-data:
    driver: local