version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=osm-db
      - MYSQL_ROOT_PASSWORD=${OSM_DB_PWD}
      - MYSQL_USER=osm-user
      - MYSQL_PASSWORD=${OSM_DB_PWD}
    ports:
      - ${OSM_DB_PORT}:3306
    expose:
      - ${OSM_DB_PORT}
    container_name: osm-database
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local